let feeds = [
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-04-04T18:08:10Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/f80f2120a24aaf4e4c9f575980dda66bd21fe5e7",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-04-04T18:05:16Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/cfd0aa272c2c6e11401c5c9525061e5f4c090fdd",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-04-04T03:30:14Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/544d3115e9ca543bb8062d40ff363846ba10f9b5",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-31T19:57:28Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/f1b60675a65ceb003bd25ba2ba849a4c88abe36a",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-31T19:43:37Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/878da5ccc78e91a86e1098029862716d6c03ccd7",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:21:44Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/d5e975c17fbecf732a0d78a01c2668f6fd329ef0",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T04:20:51Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/a9b3d15a72a0664429747acf74a7ecf018dd5c8a",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:11:10Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/3cc0dae96a035856f9be7bbe51e586567bb9ef48",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:07:45Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/4eb4e0972bdd24f9207ccf2c2c339d862a851e4f",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:07:11Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/03f0d504fde389236159bc4d9fb5f6ade7d0618b",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:04:33Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/6b54f19c2c50724fb4ffc417211bc3ca93ea7bf9",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T04:01:56Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/e7ae714cf08cd28aa952d55a081b171304f98bd3",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T04:00:43Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/7de6c3d2ecc8f0d933f1a4cc6d15b7300259e3f6",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T03:56:49Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/bb587b0e83ae0b5003c0fabfcc25ec32cd6aa3a0",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Update README.md",
    tublianDate: "2023-03-14T03:55:56Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/10e8c7cc06e34e85ac778b0592b4889ff3528833",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T03:53:01Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/5d284fe4935938fdc87189bf0fd60feead804b7e",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T03:30:20Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/d332e5426eb5751c5c5ac437b52422f284105d6c",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T03:13:16Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/e62724f039e6b4e90d6037c1b4b4362b242ad3d9",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T03:07:09Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/716e5aaa58b775000fd63bb946c41ff2df58b34d",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-14T02:17:33Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/6f7c94f2444f0f5734bc3d7d5ef844e78fd4379a",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-13T22:11:47Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/1382def337c4acd1cf4af3e906b203caad830451",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhuri",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-03-13T22:11:11Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/017edd3a09d461ad6f68cb7c181d3909c63bc2c0",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhurX",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-04-04T18:08:10Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/f80f2120a24aaf4e4c9f575980dda66bd21fe5e7",
  },
  {
    githubEvent: "PushEvent",
    emailAddresses: ["nraychaudhuri@gmail.com"],
    repoName: "nraychaudhuri/nraychaudhurX",
    title: "Updating the readme file with Tublian profile",
    tublianDate: "2023-04-04T18:08:10Z",
    type: "github",
    login: "nraychaudhuri",
    url: "https://github.com/nraychaudhuri/nraychaudhuri/commit/f80f2120a24aaf4e4c9f575980dda66bd21fe5e7",
  },
];

type FeedProps  ={
    githubEvent: string,
    emailAddresses: string[],
    repoName: string,
    title: string,
    tublianDate: string,
    type: string,
    login: string,
    url: string
  }
export {feeds, FeedProps}